---
name: CI

on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}

  build:
    # The type of runner that the job will run on
    needs: create_release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            file_name: jamsomeware
          - os: windows-latest
            file_name: jamsomeware.exe

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pyinstaller pipenv
          pipenv lock -r > requirements.txt
          pip install -r requirements.txt

      - name: Package Application
        run: pyinstaller --onefile --dist dist -n jamsomeware jamsomware.py

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/${{ matrix.file_name }}
          asset_name: ${{ matrix.file_name }}
